version: '2'
services:
  influxdb-backend-a:
    image: influxdb:1.5-alpine
    environment:
      PRE_CREATE_DB: "mydb"
  influxdb-backend-b:
    image: influxdb:1.5-alpine
    environment:
      PRE_CREATE_DB: "mydb"
  influxdb-relay-a:
    build: .
    image: ahibbitt/influxdb-relay
    environment:
      HTTP_BACKEND_influxdba: influxdb-backend-a:8086
      HTTP_BACKEND_influxdbb: influxdb-backend-b:8086
    depends_on:
      - influxdb-backend-a
      - influxdb-backend-b
  influxdb-relay-b:
    build: .
    image: ahibbitt/influxdb-relay
    environment:
      HTTP_BACKEND_influxdba: influxdb-backend-a:8086
      HTTP_BACKEND_influxdbb: influxdb-backend-b:8086
    depends_on:
      - influxdb-backend-a
      - influxdb-backend-b